services:
  # 1. Zookeeper: Required by Kafka to coordinate the cluster
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # 2. Kafka Broker
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    healthcheck:
      test: [ "CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      # Connection to Zookeeper
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # Ports to access from the outside (Your PC)
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092

      # Internal ports of the Docker Network
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://0.0.0.0:9092

      # Topic to create automatically
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

      # Important for Python/PHP services to resolve 'kafka:29092'
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

  # 3. Producer Service (PHP/Laravel)
  producer:
    build:
      context: ./producer-php-api # Search for Dockerfile in this folder
      dockerfile: Dockerfile
    container_name: producer-php-api
    ports:
      - "8000:80" # Access from outside: localhost:8000
    volumes:
      - ./producer-php-api:/var/www/html # Mount the code for development
    depends_on:
      kafka:
        condition: service_healthy

  # 4. Consumer Service (Python Worker)
  consumer:
    build:
      context: ./consumer-python-worker # Search for Dockerfile in this folder
      dockerfile: Dockerfile
    container_name: consumer-python-worker # Comment this line if you need to run multiple consumers
    # No needs ports if it's an internal worker
    volumes:
      - ./consumer-python-worker:/app # Mount the code for development
    depends_on:
      kafka:
        condition: service_healthy
      producer:
        condition: service_started
    environment:
      PYTHONUNBUFFERED: 1
    # Ensure this container runs continuously
    command: python main.py # Or the command to start your script/worker

  # 5. Kafka UI Interface
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kafka-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      # Schema Registry URL
      # KAFKA_CLUSTERS_0_SCHEMAREGISTRY: 'http://schema-registry:8081'
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_READONLY: 'true'
    depends_on:
      kafka:
        condition: service_healthy
      zookeeper:
        condition: service_started
